// Copyright 2021 Danggeun Market Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: daangn/eboolkiq/queue.proto

package pb

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Queue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *Queue) Reset() {
	*x = Queue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_daangn_eboolkiq_queue_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Queue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Queue) ProtoMessage() {}

func (x *Queue) ProtoReflect() protoreflect.Message {
	mi := &file_daangn_eboolkiq_queue_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Queue.ProtoReflect.Descriptor instead.
func (*Queue) Descriptor() ([]byte, []int) {
	return file_daangn_eboolkiq_queue_proto_rawDescGZIP(), []int{0}
}

func (x *Queue) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_daangn_eboolkiq_queue_proto protoreflect.FileDescriptor

var file_daangn_eboolkiq_queue_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x64, 0x61, 0x61, 0x6e, 0x67, 0x6e, 0x2f, 0x65, 0x62, 0x6f, 0x6f, 0x6c, 0x6b, 0x69,
	0x71, 0x2f, 0x71, 0x75, 0x65, 0x75, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x64,
	0x61, 0x61, 0x6e, 0x67, 0x6e, 0x2e, 0x65, 0x62, 0x6f, 0x6f, 0x6c, 0x6b, 0x69, 0x71, 0x22, 0x1b,
	0x0a, 0x05, 0x51, 0x75, 0x65, 0x75, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x42, 0x42, 0x0a, 0x13, 0x63,
	0x6f, 0x6d, 0x2e, 0x64, 0x61, 0x61, 0x6e, 0x67, 0x6e, 0x2e, 0x65, 0x62, 0x6f, 0x6f, 0x6c, 0x6b,
	0x69, 0x71, 0x42, 0x0a, 0x51, 0x75, 0x65, 0x75, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01,
	0x5a, 0x1d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x64, 0x61, 0x61,
	0x6e, 0x67, 0x6e, 0x2f, 0x65, 0x62, 0x6f, 0x6f, 0x6c, 0x6b, 0x69, 0x71, 0x2f, 0x70, 0x62, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_daangn_eboolkiq_queue_proto_rawDescOnce sync.Once
	file_daangn_eboolkiq_queue_proto_rawDescData = file_daangn_eboolkiq_queue_proto_rawDesc
)

func file_daangn_eboolkiq_queue_proto_rawDescGZIP() []byte {
	file_daangn_eboolkiq_queue_proto_rawDescOnce.Do(func() {
		file_daangn_eboolkiq_queue_proto_rawDescData = protoimpl.X.CompressGZIP(file_daangn_eboolkiq_queue_proto_rawDescData)
	})
	return file_daangn_eboolkiq_queue_proto_rawDescData
}

var file_daangn_eboolkiq_queue_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_daangn_eboolkiq_queue_proto_goTypes = []interface{}{
	(*Queue)(nil), // 0: daangn.eboolkiq.Queue
}
var file_daangn_eboolkiq_queue_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_daangn_eboolkiq_queue_proto_init() }
func file_daangn_eboolkiq_queue_proto_init() {
	if File_daangn_eboolkiq_queue_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_daangn_eboolkiq_queue_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Queue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_daangn_eboolkiq_queue_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_daangn_eboolkiq_queue_proto_goTypes,
		DependencyIndexes: file_daangn_eboolkiq_queue_proto_depIdxs,
		MessageInfos:      file_daangn_eboolkiq_queue_proto_msgTypes,
	}.Build()
	File_daangn_eboolkiq_queue_proto = out.File
	file_daangn_eboolkiq_queue_proto_rawDesc = nil
	file_daangn_eboolkiq_queue_proto_goTypes = nil
	file_daangn_eboolkiq_queue_proto_depIdxs = nil
}
